create_cart_table = "CREATE TABLE \"cart\" ( id varchar PRIMARY KEY NOT NULL );"
create_item_table = "CREATE TABLE \"item\" ( external_id varchar, name varchar, value integer, cart_id varchar, PRIMARY KEY (external_id, cart_id) );"
create_cart = "INSERT INTO cart ( id ) VALUES ( \'{}\' );"
create_item = "INSERT INTO item ( external_id, name, value, cart_id ) VALUES ( \'{}\', \'{}\', \'{}\', \'{}\' );"
update_item = "UPDATE item SET name=\'{}\',value=\'{}\' WHERE item.external_id=\'{}\' AND item.cart_id=\'{}\';"
get_item = "SELECT * FROM item WHERE item.external_id=\'{}\' AND item.cart_id=\'{}\';"
